stages:
  - lint
  - codestyle
  - tarballs

## Stage lint

# PHP lint
create_php_lint_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/phpcodesniffer-cli:fd-php8
  stage: lint
  only:
    - branches
  script:
    - find . -type f -name '*.php' -o -name '*.inc' -print0 | xargs -0 -n1 php -l

## Stage codestyle

# PHP codesniffer
create_php_code_sniffer_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/phpcodesniffer-cli:fd-php8
  stage: codestyle
  only:
    - branches
  script:
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - find . -type f -name '*.php' -o -name '*.inc' > ./filelist
    - /root/.composer/vendor/bin/phpcs --standard=../dev-tools/php-codesniffer-rules/FDStandard/ruleset.xml --file-list=./filelist
    - /root/.composer/vendor/bin/phpcs --config-set installed_paths /PHPCompatibility,/PHPCSUtils
    - /root/.composer/vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion $PHP_COMPATIBILITY --file-list=./filelist

# phpstan
create_phpstan_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/phpstan-cli:fd-php8
  stage: codestyle
  only:
    - branches
  script:
    - test "$SKIP_PHPSTAN" -eq 1 && exit 0
    - apt install smarty4
    - test -d ../dev-tools/ && rm -Rf ../dev-tools/
    - git clone --depth 1 https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools -b php8
    - composer global require phpstan/phpstan
    - cp ../dev-tools/phpstan/fusiondirectory/1.6/*.neon .
    - /root/.composer/vendor/bin/phpstan analyse -c phpstan.neon

build-tarballs:
  stage: tarballs
  only:
    - php8
  script:
    - mkdir ../fusiondirectory-$VERSION/
    - mv ./* ../fusiondirectory-$VERSION/
    - mv  ../fusiondirectory-$VERSION/ ./
    - tar -cvzf fusiondirectory-$VERSION.tar.gz *
  artifacts:
    paths:
      - fusiondirectory-$VERSION.tar.gz
    expire_in: 30d
