=head1 NAME

fusiondirectory-setup - class cache and locale setup for FusionDirectory

=head1 SYNOPSIS

fusiondirectory-setup [OPTION]

=head1 DESCRIPTION

fusiondirectory-setup is a command that help you to manage your fusiondirectory instance

=over 3

=item B<rescan-i18n>       Rebuilds the translations

=item B<rescan-classes>    Rebuilds the class list

=back

=head1 BUGS

Please report any bugs, or post any suggestions, to the fusiondirectory mailing list fusiondirectory-users or to 
<https://forge.fusiondirectory.org/projects/fdirectory/issues/new>


=head1 LICENCE AND COPYRIGHT

This code is part of FusionDirectory <http://www.fusiondirectory.org>

=over 2

=item Copyright (C) 2003-2010 GONICUS GmbH

=item Copyright (C) 2011 FusionDirectory Project

=back

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

=cut

