=head1 NAME

fusiondirectory-encrypt-passwords - Encrypt your fusiondirectory.conf passwords with a master password

=head1 SYNOPSIS

fusiondirectory-encrypt-passwords

=head1 DESCRIPTION

fusiondirectory-encrypt-passwords is a script to encrypt your fusiondirectory.conf passwords
with a master password. Your passwords are then only readable by the fusiondirectory
location.

=head1 BUGS

Please report any bugs, or post any suggestions, to the fusiondirectory mailing list fusiondirectory-users or to
<https://forge.fusiondirectory.org/projects/fdirectory/issues/new>


=head1 LICENCE AND COPYRIGHT

This code is part of FusionDirectory <http://www.fusiondirectory.org>

=over 2

=item Copyright (C) 2003-2010 GONICUS GmbH

=item Copyright (C) 2011-2013 FusionDirectory project

=back

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

=cut

