gofon/admin			/usr/share/fusiondirectory/plugins
gofon/gofon			/usr/share/fusiondirectory/plugins
gofon/help/guide.xml		/usr/share/fusiondirectory/doc/plugins/gofon
gofon/locale			/usr/share/fusiondirectory/locale/plugins/gofon
gofon/contrib			/usr/share/doc/fusiondirectory-plugin-gofon
gofon/html/images		/usr/share/fusiondirectory/html/plugins/gofon
gofon/etc/asterisk/*.conf	/etc/fusiondirectory/asterisk
